// Generated by contract.py. Runtime constraints remain in JSON Schema.
// Catalog is official snapshot data; PlannerState is separate user-owned data.

export type Source = {
  url: string | null;
  page: number | null;
};

export type Program = {
  scopeId: string;
  faculty: string | null;
  department: string | null;
  course: string | null;
  displayName: string;
  isCommon: boolean;
};

export type Course = {
  id: string;
  canonicalName: string;
  identityStatus: "provisional";
};

export type Mapping = {
  mappingId: string;
  scopeId: string;
  faculty: string | null;
  department: string | null;
  course: string | null;
  category: string;
  field: string | null;
  requirementType: string | null;
  curriculumCredits: number | null;
  eligibleYears: Array<number> | null;
  schoolingOnly: boolean;
  mediaOnly: boolean;
  source: Source;
};

export type Offering = {
  id: string;
  courseId: string | null;
  academicYear: 2026;
  name: string;
  method: "correspondence" | "schooling";
  subjectCode: string | null;
  classCode: string | null;
  credits: number | null;
  deliveryCategory: string | null;
  period: string | null;
  faculty: string | null;
  department: string | null;
  eligibleYears: Array<number> | null;
  resolutionStatus: "matched" | "manual_review" | "outside_mapping_scope";
  mappingIds: Array<string>;
  source: Source;
};

export type RuleTarget = {
  course_name?: string;
  curriculum_category?: string;
  curriculum_field?: string;
  requirement_type?: string;
  credit_source?: string;
  program?: string;
  course_names?: Array<string>;
};

export type RuleConditions = {
  max_enrollments?: number;
  min_enrollments?: number;
  min_courses?: number;
  credits_per_course?: number;
  choose_count?: number;
  max_languages_counted?: number;
  marker_source_page?: number;
  requires_completed_courses?: number;
  aggregate?: boolean;
  same_language_as_foreign_requirement?: boolean;
  same_language?: boolean;
  includes_thesis?: boolean;
  full_course_credits_required?: boolean;
  partial_two_credits_countable?: boolean;
  general_total_unaffected?: boolean;
  exclude_schooling_required?: boolean;
  double_count?: boolean;
  before?: string;
  group_by?: string;
  applies_to?: string;
  exclude_table_marker?: string;
  method?: "correspondence" | "schooling";
  transfer?: "excess_only";
  options?: Array<string>;
  combine_categories?: Array<string>;
  excluded_categories?: Array<string>;
  when?: {
  thesis_selected: boolean;
};
  from?: RuleTarget;
  to?: RuleTarget;
  threshold?: {
  credits: number;
};
};

export type StructuredRequirement = {
  id: string;
  ruleId: string;
  scopeId: string;
  sourcePage: number | null;
  status: "structured";
  ruleType: "required_course" | "min_credits" | "max_credits" | "overflow_credit_transfer" | "min_schooling_credits" | "min_courses" | "exact_credits" | "choose_one";
  target: RuleTarget;
  value: number | null;
  unit: string | null;
  conditions: RuleConditions | null;
};

export type UnsupportedRequirement = {
  id: string;
  ruleId: string;
  scopeId: null;
  sourcePage: number | null;
  status: "unsupported";
  ruleType: null;
  target: null;
  value: null;
  unit: null;
  conditions: null;
  scopeLabel: string;
  category: string | null;
  reason: string;
};

export type Requirement = StructuredRequirement | UnsupportedRequirement;

export type Coverage = {
  offeringCount: number;
  mappingCount: number;
  mappingEdgeCount: number;
  matchedOfferingCount: number;
  manualReviewOfferingCount: number;
  outsideMappingScopeOfferingCount: number;
  courseIdPresentOfferingCount: number;
  courseIdNullOfferingCount: number;
  allSnapshotOfferingsSelectable: true;
  scope: "2026_input_snapshot_only";
};

export type Metadata = {
  graduationCheckComplete: false;
  structuredRequirementCount: number;
  unsupportedRequirementCount: number;
  unresolvedOfferingCount: number;
  unresolvedOfferingMeaning: "no_curriculum_mapping: manual_review + outside_mapping_scope; independent_of_courseId";
  provisionalCourseCount: number;
  catalogCoverage: Coverage;
  requirementEvaluationDefault: "unknown";
  unsupportedScopePolicy: "retain_all_warnings_until_scope_is_verified";
  sourceLinksReverified: false;
};

export type PlannerCatalog = {
  schemaVersion: 1;
  academicYear: 2026;
  generatedFromSnapshot: "hosei-2026-v1-postgresql-import";
  programs: Array<Program>;
  courses: Array<Course>;
  mappings: Array<Mapping>;
  offerings: Array<Offering>;
  requirements: Array<Requirement>;
  metadata: Metadata;
};

export type PlannerItem = {
  offeringId: string;
  status: "planned" | "in_progress" | "waiting" | "earned" | "failed" | "dropped";
  plannedYear: number | null;
  plannedTerm: string | null;
  /** Only used for 2026 史学演習 offerings. The learner records the confirmed completion order. */
  earnedOrder: 1 | 2 | 3 | 4 | null;
};

export type PlannerTodo = {
  id: string;
  offeringId: string | null;
  text: string;
  done: boolean;
};

export type PlannerState = {
  schemaVersion: 2;
  selectedScopeId: string | null;
  items: Array<PlannerItem>;
  todos: Array<PlannerTodo>;
};

export type RequirementEvaluation = {
  requirementId: string;
  result: "satisfied" | "unsatisfied" | "unknown";
  reason: string | null;
};

export type GraduationEvaluation = {
  result: "unknown";
  reason: string;
};
