import { useState } from 'react';
import type { GraduationProfile, RecognitionMode } from '../../planner/plannerCatalog';
import { GRADUATION_PROFILE_PREREQUISITE_LABEL, graduationProfileValidationError, missingGraduationProfilePrerequisites, normalizeAdmissionYear, normalizeNonnegativeNumber, officialRecognitionPrefill } from '../../planner/graduationProfile';

type Props = { profile: GraduationProfile; disabled: boolean; onChange: (profile: GraduationProfile) => void };
const modes: Array<[RecognitionMode, string]> = [['unknown', '未確認'], ['none', 'なし'], ['recognized', '認定'], ['exempt', '免除']];

export default function GraduationProfileSettings(props: Props) { return <Form key={JSON.stringify(props.profile.recognizedCredits)} {...props} />; }
function Form({ profile, disabled, onChange }: Props) {
  const [error, setError] = useState<string | null>(null);
  const update = (next: GraduationProfile) => { const message = graduationProfileValidationError(next); if (message) setError(message); else { setError(null); onChange(next); } };
  const field = (key: 'humanities' | 'social' | 'natural', label: string) => <label className="grid gap-1 text-sm">{label}<select value={profile.recognizedCredits.general[key].mode} disabled={disabled} onChange={e => update({ ...profile, recognizedCredits: { ...profile.recognizedCredits, general: { ...profile.recognizedCredits.general, [key]: { mode: e.target.value as RecognitionMode, credits: e.target.value === 'exempt' ? null : profile.recognizedCredits.general[key].credits } } } })} className="border p-2">{modes.map(([v, n]) => <option key={v} value={v}>{n}</option>)}</select><input aria-label={`${label}認定単位`} type="number" min="0" value={profile.recognizedCredits.general[key].credits ?? ''} disabled={disabled || profile.recognizedCredits.general[key].mode === 'exempt'} onBlur={e => update({ ...profile, recognizedCredits: { ...profile.recognizedCredits, general: { ...profile.recognizedCredits.general, [key]: { ...profile.recognizedCredits.general[key], credits: normalizeNonnegativeNumber(e.currentTarget.value) } } } })} onChange={() => undefined} className="border p-2" placeholder="単位" /></label>;
  const simple = (key: 'foreignLanguage' | 'physicalEducation', label: string, max: number) => <label className="grid gap-1 text-sm">{label}<select value={profile.recognizedCredits[key].mode} disabled={disabled} onChange={e => update({ ...profile, recognizedCredits: { ...profile.recognizedCredits, [key]: { ...profile.recognizedCredits[key], mode: e.target.value as RecognitionMode, credits: e.target.value === 'exempt' ? null : profile.recognizedCredits[key].credits } } })} className="border p-2">{modes.map(([v, n]) => <option key={v} value={v}>{n}</option>)}</select><input aria-label={`${label}認定単位`} type="number" min="0" max={max} value={profile.recognizedCredits[key].credits ?? ''} disabled={disabled || profile.recognizedCredits[key].mode === 'exempt'} onBlur={e => update({ ...profile, recognizedCredits: { ...profile.recognizedCredits, [key]: { ...profile.recognizedCredits[key], credits: normalizeNonnegativeNumber(e.currentTarget.value) } } })} onChange={() => undefined} className="border p-2" placeholder="公式認定単位" /></label>;
  const missing = missingGraduationProfilePrerequisites(profile);
  return <section aria-labelledby="graduation-profile-heading" className="bg-white border border-gray-200 p-5 sm:p-7"><h2 id="graduation-profile-heading" className="text-xl text-[#002255]">卒業判定・編入認定設定</h2><p className="mt-3 border-l-4 border-sky-600 bg-sky-50 p-3 text-sm">公式の認定結果を正として入力します。未入力を0単位とは扱いません。免除は修得単位に加えません。</p>
    <div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="grid gap-1 text-sm">入学年度<input aria-label="入学年度" type="number" defaultValue={profile.admissionYear ?? ''} disabled={disabled} onBlur={e => update({ ...profile, admissionYear: normalizeAdmissionYear(e.currentTarget.value) })} className="border p-2" /></label><label className="grid gap-1 text-sm">入学区分<select aria-label="入学区分" value={profile.admissionType} disabled={disabled} onChange={e => update({ ...profile, admissionType: e.target.value as GraduationProfile['admissionType'] })} className="border p-2"><option value="unknown">未選択</option><option value="first_year">1年次入学</option><option value="transfer_second_year">2年次編入</option><option value="transfer_third_year">3年次編入</option><option value="bachelor_admission">学士入学</option><option value="hosei_internal_transfer">法政内部等（個別認定）</option><option value="other_transfer">その他・個別認定</option></select></label></div>
    {['transfer_second_year', 'transfer_third_year', 'bachelor_admission'].includes(profile.admissionType) && <button type="button" disabled={disabled} className="mt-4 border border-sky-700 px-3 py-2 text-sm text-sky-800" onClick={() => update({ ...profile, recognizedCredits: { ...officialRecognitionPrefill(profile.admissionType), totalCredits: profile.recognizedCredits.totalCredits } })}>公式標準値をフォームへ適用（保存）</button>}
    <fieldset className="mt-6 grid gap-3 sm:grid-cols-3"><legend className="font-medium">一般教育</legend>{field('humanities', '人文')}{field('social', '社会')}{field('natural', '自然')}</fieldset>
    <div className="mt-6 grid gap-4 sm:grid-cols-2">{simple('foreignLanguage', '外国語', 4)}{simple('physicalEducation', '保健体育', 2)}<label className="grid gap-1 text-sm">公式認定単位・合計（旧データ互換）<input aria-label="認定単位" type="number" min="0" defaultValue={profile.recognizedCredits.totalCredits ?? ''} disabled={disabled} onBlur={e => update({ ...profile, recognizedCredits: { ...profile.recognizedCredits, totalCredits: normalizeNonnegativeNumber(e.currentTarget.value) } })} className="border p-2" placeholder="内訳未配分なら参考値のみ" /></label><label className="grid gap-1 text-sm">スクーリング相当<input aria-label="認定単位のうちスクーリング相当" type="number" min="0" defaultValue={profile.recognizedCredits.schoolingEquivalentCredits ?? ''} disabled={disabled} onBlur={e => update({ ...profile, recognizedCredits: { ...profile.recognizedCredits, schoolingEquivalentCredits: normalizeNonnegativeNumber(e.currentTarget.value) } })} className="border p-2" placeholder="公式に判明する場合のみ" /></label></div>
    <p className="mt-4 text-xs text-gray-700">専門教育の個別認定は、2026カタログ上のidentityを確認できる場合だけ卒業要件に算入します。曖昧な科目は個別確認として保持し、自動で区分を決めません。</p><label className="mt-5 grid gap-1 text-sm">適用課程<select aria-label="適用課程" value={profile.curriculumApplicability} disabled={disabled} onChange={e => update({ ...profile, curriculumApplicability: e.target.value as GraduationProfile['curriculumApplicability'] })} className="border p-2"><option value="unknown">未選択（確認が必要）</option><option value="current_2026">2026年度の現行課程</option><option value="legacy_or_transition">旧課程・経過措置・個別適用</option></select></label>{error && <p role="alert" className="mt-4 text-sm text-red-700">{error} 変更は保存していません。</p>}{missing.length > 0 && <p className="mt-4 text-sm text-amber-800">判定前に確認が必要：{missing.map(key => GRADUATION_PROFILE_PREREQUISITE_LABEL[key]).join('、')}</p>}</section>;
}
