import { groupImportedAchievements, type ImportedCourseAchievement, type ImportedStudyRecord } from '../../planner/gradeImportApply';
import type { Offering } from '../../planner/plannerCatalog';

const methodLabel = (method: ImportedStudyRecord['method']) => method === 'correspondence' ? '通信' : 'スクーリング';
const matchLabel = (match: ImportedStudyRecord['match']) => match === 'exact_unique' ? '既存科目一致' : match === 'ambiguous' ? '要確認' : '未一致';
const yearLabel = (source: ImportedStudyRecord['yearSource']) => source === 'source' ? '成績表の年度' : source === 'inferred' ? '推定' : source === 'manual' ? '手動修正' : '未設定';

export default function ImportedAchievements({ records, courseRows = [], offerings, disabled, onChange, onChangeCourse, onDelete }: { records: ImportedStudyRecord[]; courseRows?: ImportedCourseAchievement[]; offerings: Offering[]; disabled: boolean; onChange: (id: string, patch: Partial<ImportedStudyRecord>) => void; onChangeCourse: (id: string, patch: Partial<ImportedCourseAchievement>) => void; onDelete: (id: string) => void }) {
  if (!records.length && !courseRows.length) return null;
  return <section id="imported-achievements" className="border border-[#002255] bg-white p-4 space-y-4" aria-label="取り込んだ履修実績">
    <div><h2 className="text-lg text-[#002255]">取り込んだ履修実績</h2><p className="text-sm">成績表から保存した項目です。年度・期・照合先はここで後から修正できます。</p></div>
    <section className="space-y-2"><h3 className="border-b border-gray-200 pb-1 text-base">成績表の科目行</h3><p className="text-xs text-gray-600">公式の修得単位の正本です。詳細の通信・スクーリング記録がなくても保持されます。ここで選ぶ照合先は詳細記録より優先します。</p>{courseRows.map(row => { const candidates = offerings.filter(offering => row.candidateOfferingIds.includes(offering.id)); return <article key={row.id} className="border border-orange-200 bg-orange-50 p-3 text-sm"><p className="font-medium">{row.rawName}</p><p className="mt-1">修得 {row.earnedCreditsTotal ?? '不明'}単位 / S {row.schoolingCreditsTotal ?? '不明'}単位 / 構成 {row.compositionCredits ?? '不明'}単位</p><label className="mt-2 block">行の照合先 <select disabled={disabled} value={row.selectedOfferingId ?? ''} onChange={event => { const selectedOfferingId = event.target.value || null; const offering = offerings.find(value => value.id === selectedOfferingId); onChangeCourse(row.id, { selectedOfferingId, courseId: offering?.courseId ?? null, match: offering?.courseId && offering.resolutionStatus === 'matched' ? 'exact_unique' : selectedOfferingId ? 'ambiguous' : 'unmatched' }); }} className="ml-2 max-w-full border p-1"><option value="">選ばない（区分・要件は未確定）</option>{candidates.map(candidate => <option key={candidate.id} value={candidate.id}>{candidate.name}（{candidate.period ?? '期未設定'}）</option>)}</select></label><p className="mt-1 text-xs text-gray-600">照合: {matchLabel(row.match)}{row.selectedOfferingId ? ' / 照合先あり' : ' / 未設定'}{row.categoryRaw ? ` / 成績表区分: ${row.categoryRaw}` : ''}</p></article>; })}</section>
    {groupImportedAchievements(records).map(([year, group]) => <div key={year ?? 'unset'} className="space-y-2"><h3 className="border-b border-gray-200 pb-1 text-base">{year === null ? '年度未設定' : `${year}年度`}</h3>
      {group.map(record => { const linked = record.offeringId ? offerings.find(offering => offering.id === record.offeringId) : null; const candidates = offerings.filter(offering => offering.method === record.method && offering.name.trim() === record.rawName.trim()); return <article key={record.id} className="border p-3 text-sm space-y-2">
        <div className="flex flex-wrap items-baseline justify-between gap-x-3 gap-y-1"><p className="font-medium">{record.rawName} <span className="font-normal text-gray-600">— {methodLabel(record.method)}</span></p><button type="button" disabled={disabled} onClick={() => { if (window.confirm(`「${record.rawName}」の取り込んだ履修実績を削除しますか？`)) onDelete(record.id); }} className="text-xs underline disabled:opacity-50">削除</button></div>
        <div className="grid gap-2 sm:grid-cols-2"><label>年度 <input disabled={disabled} type="number" value={record.academicYear ?? ''} onChange={event => onChange(record.id, { academicYear: event.target.value === '' ? null : Number(event.target.value), yearSource: 'manual' })} className="ml-2 w-24 border p-1" /> <span className="text-xs text-gray-600">{yearLabel(record.yearSource)}</span></label><label>期 <input disabled={disabled} value={record.term ?? ''} onChange={event => onChange(record.id, { term: event.target.value || null })} className="ml-2 w-20 border p-1" /></label></div>
        <p>日付: {record.date ?? '未設定'} / 単位: {record.credits ?? '未設定'} / 評価（成績表の項目）: {record.grade ?? '未設定'}</p>
        {record.sourceCourseId && <p className="text-xs text-gray-600">成績表の科目行: 修得単位 {record.earnedCreditsTotal ?? '不明'} / S単位 {record.schoolingCreditsTotal ?? '不明'} / 構成単位 {record.compositionCredits ?? '不明'}（この合計は取込元の事実として編集できません）</p>}
        <label className="block">照合先 <select disabled={disabled} value={record.offeringId ?? ''} onChange={event => onChange(record.id, { offeringId: event.target.value || null })} className="ml-2 max-w-full border p-1"><option value="">選ばない（Imported Course実績として保存）</option>{candidates.map(candidate => <option key={candidate.id} value={candidate.id}>{candidate.name}（{candidate.period ?? '期未設定'}）</option>)}</select></label>
        <p className="text-xs text-gray-600">{matchLabel(record.match)}{linked ? ` / 紐づけ: ${linked.name}（${linked.period ?? '期未設定'}）` : ' / 新規Imported Course実績'} / 取込元: 法政成績表</p>
        {record.method === 'correspondence' && <details className="text-xs"><summary className="cursor-pointer">リポート・試験の詳細</summary><p className="mt-1">リポート: {record.reports?.map(report => report.raw || report.status).filter(Boolean).join(' / ') || '記録なし'} / 単位修得試験: {record.examGrade ?? '未設定'}</p></details>}
        <p className="text-xs text-gray-600">この評価は最終評価ではありません。履修計画・卒業要件・修得状態は変更しません。</p>
      </article>; })}
    </div>)}
  </section>;
}
