import { useState } from 'react';
import { normalizeAdmissionYear } from '../../planner/graduationProfile';
import { isStandardTerm, STANDARD_TERMS, statusLabels } from '../../planner/planTable';
import { COURSE_GRADES, gradeLabel } from '../../planner/courseEvaluations';
import { isHistoryCompletionOrderCourse, isHistoricalSources, isHistorySeminar } from '../../planner/historySeminar';
import type { CourseGrade, Offering, PlannerItem } from '../../planner/plannerCatalog';

const control = 'w-full rounded-sm border border-gray-300 bg-white p-2 text-sm disabled:opacity-50';
const yearOptions = [1, 2, 3, 4] as const;

export function TermSelect({ value, disabled, onChange, id }: { value: string | null; disabled: boolean; onChange: (value: string | null) => void; id: string }) { const legacy = value !== null && !isStandardTerm(value); return <select id={id} value={value ?? ''} disabled={disabled} onChange={event => onChange(event.target.value || null)} className={control}><option value="">未設定</option>{legacy && <option value={value!}>保存済み：{value}（要確認）</option>}{STANDARD_TERMS.map(term => <option key={term} value={term}>{term}</option>)}</select>; }
export function GradeSelect({ value, disabled, onChange, label }: { value: CourseGrade | null; disabled: boolean; onChange: (value: CourseGrade | null) => void; label: string }) { return <select aria-label={label} value={value ?? ''} disabled={disabled} onChange={event => onChange(event.target.value === '' ? null : event.target.value as CourseGrade)} className={control}><option value="">未評価</option>{COURSE_GRADES.map(grade => <option key={grade} value={grade}>{gradeLabel(grade)}</option>)}</select>; }
export function StudyYearSelect({ value, disabled, onChange }: { value: 1 | 2 | 3 | 4 | null; disabled: boolean; onChange: (value: 1 | 2 | 3 | 4 | null) => void }) { return <select value={value ?? ''} disabled={disabled} onChange={event => onChange(event.target.value === '' ? null : Number(event.target.value) as 1 | 2 | 3 | 4)} className={control}><option value="">未設定</option>{yearOptions.map(year => <option key={year} value={year}>{year}年</option>)}</select>; }
export function StatusSelect({ value, disabled, onChange }: { value: PlannerItem['status']; disabled: boolean; onChange: (value: PlannerItem['status']) => void }) { return <select value={value} disabled={disabled} onChange={event => onChange(event.target.value as PlannerItem['status'])} className={control}>{Object.entries(statusLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select>; }
export function YearInput({ value, disabled, onChange }: { value: number | null; disabled: boolean; onChange: (value: number | null) => void }) { const [draft, setDraft] = useState(value?.toString() ?? ''); const [invalid, setInvalid] = useState(false); const save = () => { const next = draft.trim(); if (next === '') { setInvalid(false); onChange(null); return; } const year = normalizeAdmissionYear(next); if (/^\d{4}$/.test(next) && year !== null) { setInvalid(false); onChange(year); return; } setInvalid(true); setDraft(value?.toString() ?? ''); }; return <><input aria-label="計画年度" inputMode="numeric" value={draft} disabled={disabled} onChange={event => { setDraft(event.target.value); setInvalid(false); }} onBlur={save} className={control} />{invalid && <span className="mt-1 block text-xs text-red-700">4桁の西暦（1000〜9999）で入力してください。</span>}</>; }
export function CompletionOrderInput({ item, offering, disabled, onChange }: { item: PlannerItem; offering: Offering; disabled: boolean; onChange: (value: number | null) => void }) {
  const [draft, setDraft] = useState(item.earnedOrder?.toString() ?? ''); const [invalid, setInvalid] = useState(false);
  if (!isHistoryCompletionOrderCourse(offering) || item.status !== 'earned') return null;
  const save = () => { const next = draft.trim(); if (next === '') { setInvalid(false); onChange(null); return; } if (/^[1-9]\d*$/.test(next)) { setInvalid(false); onChange(Number(next)); return; } setInvalid(true); setDraft(item.earnedOrder?.toString() ?? ''); };
  const family = isHistorySeminar(offering) ? '史学演習' : isHistoricalSources(offering) ? '歴史資料学' : '';
  return <label className="text-xs">{family}の修得順<input aria-label={`${family}の修得順`} inputMode="numeric" min="1" value={draft} disabled={disabled} onChange={event => { setDraft(event.target.value); setInvalid(false); }} onBlur={save} className={control} />{invalid && <span className="mt-1 block text-xs text-red-700">1以上の整数で入力してください。系列内で重複・欠番は保存できません。</span>}<span className="mt-1 block text-xs text-gray-500">修得済みだけに入力します。変更・削除できます。</span></label>;
}
