import { useState, type ReactNode } from 'react';
import ClassificationLabel from './ClassificationLabel';
import { CorrespondenceDetails } from './CorrespondenceProgress';
import type { createCreditClassifier } from '../../planner/annualPlan';
import { isStandardTerm, offeringFormLabel, progressSummaryForOffering, STANDARD_TERMS, statusLabels } from '../../planner/planTable';
import { evaluationFor, COURSE_GRADES, gradeLabel } from '../../planner/courseEvaluations';
import { isCorrespondenceOffering, progressForCorrespondence } from '../../planner/correspondenceProgress';
import { isMediaSchooling } from '../../planner/mediaSchooling';
import type { CorrespondenceCourseProgress, CourseEvaluation, CourseGrade, MediaCourseProgress, Offering, PlannerItem, PublicCourse } from '../../planner/plannerCatalog';

type Props = { classify: ReturnType<typeof createCreditClassifier>; items: PlannerItem[]; publicCourses: PublicCourse[]; offerings: Map<string, Offering>; correspondenceProgress: Record<string, CorrespondenceCourseProgress>; mediaProgress: Record<string, MediaCourseProgress>; evaluations: Record<string, CourseEvaluation>; disabled: boolean; onChange: (id: string, patch: Partial<Omit<PlannerItem, 'offeringId'>>) => void; onRemove: (id: string) => void; onChangePublicCourse: (id: string, patch: Partial<Omit<PublicCourse, 'id' | 'credits'>>) => void; onRemovePublicCourse: (id: string) => void; onChangeEvaluation: (id: string, evaluation: CourseEvaluation) => void; onChangeCorrespondence: (id: string, progress: CorrespondenceCourseProgress) => void; onOpenMedia: () => void };
const control = 'w-full rounded-sm border border-gray-300 bg-white p-2 text-sm disabled:opacity-50';
const groups: Array<[1 | 2 | 3 | 4 | null, string]> = [[1, '1年'], [2, '2年'], [3, '3年'], [4, '4年'], [null, '未設定']];
const yearOptions = [1, 2, 3, 4] as const;

function TermSelect({ value, disabled, onChange, id }: { value: string | null; disabled: boolean; onChange: (value: string | null) => void; id: string }) { const legacy = value !== null && !isStandardTerm(value); return <select id={id} value={value ?? ''} disabled={disabled} onChange={event => onChange(event.target.value || null)} className={control}><option value="">未設定</option>{legacy && <option value={value!}>保存済み：{value}（要確認）</option>}{STANDARD_TERMS.map(term => <option key={term} value={term}>{term}</option>)}</select>; }
function GradeSelect({ value, disabled, onChange, label }: { value: CourseGrade | null; disabled: boolean; onChange: (value: CourseGrade | null) => void; label: string }) { return <select aria-label={label} value={value ?? ''} disabled={disabled} onChange={event => onChange(event.target.value === '' ? null : event.target.value as CourseGrade)} className={control}><option value="">未評価</option>{COURSE_GRADES.map(grade => <option key={grade} value={grade}>{gradeLabel(grade)}</option>)}</select>; }
function StudyYearSelect({ value, disabled, onChange }: { value: 1 | 2 | 3 | 4 | null; disabled: boolean; onChange: (value: 1 | 2 | 3 | 4 | null) => void }) { return <select value={value ?? ''} disabled={disabled} onChange={event => onChange(event.target.value === '' ? null : Number(event.target.value) as 1 | 2 | 3 | 4)} className={control}><option value="">未設定</option>{yearOptions.map(year => <option key={year} value={year}>{year}年</option>)}</select>; }
function StatusSelect({ value, disabled, onChange }: { value: PlannerItem['status']; disabled: boolean; onChange: (value: PlannerItem['status']) => void }) { return <select value={value} disabled={disabled} onChange={event => onChange(event.target.value as PlannerItem['status'])} className={control}>{Object.entries(statusLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select>; }
function YearInput({ value, disabled, onChange }: { value: number | null; disabled: boolean; onChange: (value: number | null) => void }) { return <input aria-label="計画年度" inputMode="numeric" value={value ?? ''} disabled={disabled} onChange={event => { const next = event.target.value; if (next === '' || /^\d{4}$/.test(next)) onChange(next === '' ? null : Number(next)); }} className={control} />; }

function ItemRow({ item, offering, props }: { item: PlannerItem; offering: Offering; props: Props }) {
  const [open, setOpen] = useState(false); const evaluation = evaluationFor(item.offeringId, props.evaluations); const correspondence = progressForCorrespondence(offering, props.correspondenceProgress);
  const details = isCorrespondenceOffering(offering) ? <CorrespondenceDetails item={item} offering={offering} saved={correspondence} disabled={props.disabled} onChange={props.onChangeCorrespondence} /> : isMediaSchooling(offering) ? <div className="rounded-sm bg-slate-50 p-4 text-sm">回別の動画・テストはメディア進捗で編集します。<button type="button" onClick={props.onOpenMedia} className="ml-2 underline">メディア進捗で編集</button></div> : <label className="block max-w-xs text-sm">スクーリング評価（従来記録）<GradeSelect label="スクーリング評価" value={evaluation.schoolingGrade} disabled={props.disabled} onChange={schoolingGrade => props.onChangeEvaluation(item.offeringId, { ...evaluation, schoolingGrade })} /></label>;
  return <><tr className="border-b border-gray-100 align-top"><td className="p-3">{item.studyYear === null ? '未設定' : `${item.studyYear}年`}</td><td className="p-3">{item.plannedTerm === null ? '—' : isStandardTerm(item.plannedTerm) ? item.plannedTerm : '保存済み（要確認）'}</td><td className="p-3"><p className="font-medium">{offering.name}</p><ClassificationLabel value={props.classify(offering)} /><p className="mt-1 text-xs text-gray-500">{item.plannedYear === null ? '年度未設定' : `${item.plannedYear}年度`}</p></td><td className="p-3 text-center">{offering.credits ?? '—'}</td><td className="p-3">{offeringFormLabel(offering)}</td><td className="p-3"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{statusLabels[item.status]}</span><p className="mt-2 text-sm">{progressSummaryForOffering(item, offering, props.correspondenceProgress, props.mediaProgress)}</p></td><td className="p-3"><GradeSelect label={`${offering.name}の最終評価`} value={evaluation.finalGrade} disabled={props.disabled} onChange={finalGrade => props.onChangeEvaluation(item.offeringId, { ...evaluation, finalGrade })} /></td><td className="p-3 whitespace-nowrap"><button type="button" onClick={() => setOpen(value => !value)} className="underline">{open ? '閉じる' : '開く'}</button><button type="button" disabled={props.disabled} onClick={() => props.onRemove(item.offeringId)} className="ml-3 text-red-700 underline">削除</button></td></tr>{open && <tr className="border-b border-gray-200"><td colSpan={8} className="p-4"><div className="grid gap-2 sm:grid-cols-4"><label className="text-xs">年度<YearInput value={item.plannedYear} disabled={props.disabled} onChange={plannedYear => props.onChange(item.offeringId, { plannedYear })} /></label><label className="text-xs">履修学年<StudyYearSelect value={item.studyYear} disabled={props.disabled} onChange={studyYear => props.onChange(item.offeringId, { studyYear })} /></label><label className="text-xs">時期<TermSelect id={`term-${item.offeringId}`} value={item.plannedTerm} disabled={props.disabled} onChange={plannedTerm => props.onChange(item.offeringId, { plannedTerm })} /></label><label className="text-xs">状態<StatusSelect value={item.status} disabled={props.disabled} onChange={status => props.onChange(item.offeringId, { status })} /></label></div><div className="mt-3">{details}</div></td></tr>}</>;
}
function PublicRow({ course, props }: { course: PublicCourse; props: Props }) { const [open, setOpen] = useState(false); const [title, setTitle] = useState(course.title); return <><tr className="border-b border-gray-100 align-top"><td className="p-3">{course.studyYear === null ? '未設定' : `${course.studyYear}年`}</td><td className="p-3">{course.plannedTerm === null ? '—' : isStandardTerm(course.plannedTerm) ? course.plannedTerm : '保存済み（要確認）'}</td><td className="p-3"><p className="font-medium">{course.title}</p><p className="text-xs text-gray-500">公開科目 / {course.plannedYear ?? '年度未設定'}年度</p></td><td className="p-3 text-center">2</td><td className="p-3">公開科目</td><td className="p-3"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{statusLabels[course.status]}</span></td><td className="p-3"><GradeSelect label={`${course.title}の最終評価`} value={course.finalGrade} disabled={props.disabled} onChange={finalGrade => props.onChangePublicCourse(course.id, { finalGrade })} /></td><td className="p-3 whitespace-nowrap"><button type="button" onClick={() => setOpen(value => !value)} className="underline">{open ? '閉じる' : '開く'}</button><button type="button" disabled={props.disabled} onClick={() => props.onRemovePublicCourse(course.id)} className="ml-3 text-red-700 underline">削除</button></td></tr>{open && <tr><td colSpan={8} className="p-4"><div className="grid gap-2 sm:grid-cols-5"><label className="text-xs">科目名<input value={title} disabled={props.disabled} onChange={event => setTitle(event.target.value)} onBlur={() => title.trim() && props.onChangePublicCourse(course.id, { title: title.trim() })} className={control} /></label><label className="text-xs">年度<YearInput value={course.plannedYear} disabled={props.disabled} onChange={plannedYear => props.onChangePublicCourse(course.id, { plannedYear })} /></label><label className="text-xs">履修学年<StudyYearSelect value={course.studyYear} disabled={props.disabled} onChange={studyYear => props.onChangePublicCourse(course.id, { studyYear })} /></label><label className="text-xs">時期<TermSelect id={`public-term-${course.id}`} value={course.plannedTerm} disabled={props.disabled} onChange={plannedTerm => props.onChangePublicCourse(course.id, { plannedTerm })} /></label><label className="text-xs">状態<StatusSelect value={course.status} disabled={props.disabled} onChange={status => props.onChangePublicCourse(course.id, { status })} /></label></div></td></tr>}</>; }
function MobileCard({ children }: { children: ReactNode }) { return <div className="border-b border-gray-200 p-4 last:border-b-0">{children}</div>; }
function MobileItemCard({ item, offering, props }: { item: PlannerItem; offering: Offering; props: Props }) { const [open, setOpen] = useState(false); const evaluation = evaluationFor(item.offeringId, props.evaluations); const correspondence = progressForCorrespondence(offering, props.correspondenceProgress); return <MobileCard><p className="font-medium">{offering.name} {offering.credits ?? '—'}単位</p><p className="mt-1 text-sm">{offeringFormLabel(offering)} / {item.studyYear ?? '未設定'}年 / {item.plannedTerm ?? '時期未設定'}</p><ClassificationLabel value={props.classify(offering)} /><p className="mt-2 text-sm">{progressSummaryForOffering(item, offering, props.correspondenceProgress, props.mediaProgress)}</p><p className="mt-2 text-xs">{statusLabels[item.status]}</p><label className="mt-2 block text-sm">最終評価<GradeSelect label={`${offering.name}の最終評価`} value={evaluation.finalGrade} disabled={props.disabled} onChange={finalGrade => props.onChangeEvaluation(item.offeringId, { ...evaluation, finalGrade })} /></label><button type="button" onClick={() => setOpen(value => !value)} className="mt-3 text-sm underline">{open ? '詳細を閉じる' : '詳細を開く'}</button><button type="button" onClick={() => props.onRemove(item.offeringId)} className="ml-3 text-sm text-red-700 underline">削除</button>{open && <div className="mt-3 border-t border-gray-200 pt-3"><div className="grid gap-2"><label className="text-xs">年度<YearInput value={item.plannedYear} disabled={props.disabled} onChange={plannedYear => props.onChange(item.offeringId, { plannedYear })} /></label><label className="text-xs">履修学年<StudyYearSelect value={item.studyYear} disabled={props.disabled} onChange={studyYear => props.onChange(item.offeringId, { studyYear })} /></label><label className="text-xs">時期<TermSelect id={`mobile-term-${item.offeringId}`} value={item.plannedTerm} disabled={props.disabled} onChange={plannedTerm => props.onChange(item.offeringId, { plannedTerm })} /></label><label className="text-xs">状態<StatusSelect value={item.status} disabled={props.disabled} onChange={status => props.onChange(item.offeringId, { status })} /></label></div>{isCorrespondenceOffering(offering) ? <div className="mt-3"><CorrespondenceDetails item={item} offering={offering} saved={correspondence} disabled={props.disabled} onChange={props.onChangeCorrespondence} /></div> : isMediaSchooling(offering) ? <button type="button" onClick={props.onOpenMedia} className="mt-3 text-sm underline">メディア進捗で編集</button> : null}</div>}</MobileCard>; }

export default function PlannedCourseList(props: Props) { const count = props.items.length + props.publicCourses.length; return <section aria-labelledby="planned-heading" className="border border-gray-200 bg-white min-w-0"><div className="p-5 sm:p-7"><h2 id="planned-heading" className="text-xl text-[#002255]">履修計画 <span className="text-sm">{count}件</span></h2><p className="mt-2 text-sm text-gray-600">履修年度・履修学年・時期を分けて記録します。最終評価は進捗や修得状態を自動変更しません。</p></div>{count === 0 ? <p className="px-5 pb-7 text-sm text-gray-600">科目を検索して、履修計画に追加してください。</p> : groups.map(([year, label]) => { const items = props.items.filter(item => item.studyYear === year); const publicCourses = props.publicCourses.filter(course => course.studyYear === year); if (items.length + publicCourses.length === 0) return null; return <section key={label} className="border-t border-gray-200"><h3 className="bg-slate-50 px-5 py-3 font-medium text-[#002255]">{label} <span className="text-sm font-normal">{items.length + publicCourses.length}件</span></h3><div className="hidden md:block"><table className="w-full table-fixed text-sm"><thead className="text-left text-xs text-gray-600"><tr><th className="p-3 w-16">履修学年</th><th className="p-3 w-20">時期</th><th className="p-3">科目名</th><th className="p-3 w-14">単位</th><th className="p-3 w-24">履修形態</th><th className="p-3 w-56">進捗</th><th className="p-3 w-32">最終評価</th><th className="p-3 w-28">詳細</th></tr></thead><tbody>{items.map(item => <ItemRow key={item.offeringId} item={item} offering={props.offerings.get(item.offeringId)!} props={props} />)}{publicCourses.map(course => <PublicRow key={course.id} course={course} props={props} />)}</tbody></table></div><div className="md:hidden">{items.map(item => <MobileItemCard key={item.offeringId} item={item} offering={props.offerings.get(item.offeringId)!} props={props} />)}{publicCourses.map(course => <MobileCard key={course.id}><p className="font-medium">{course.title} 2単位</p><p className="mt-1 text-sm">公開科目 / {course.studyYear ?? '未設定'}年 / {course.plannedTerm ?? '時期未設定'}</p><label className="mt-2 block text-sm">最終評価<GradeSelect label={`${course.title}の最終評価`} value={course.finalGrade} disabled={props.disabled} onChange={finalGrade => props.onChangePublicCourse(course.id, { finalGrade })} /></label><button type="button" onClick={() => props.onRemovePublicCourse(course.id)} className="mt-3 text-sm text-red-700 underline">削除</button></MobileCard>)}</div></section>; })}</section>; }
