import { useState, type ReactNode } from 'react';
import type { PublicCourse } from '../../planner/plannerCatalog';
import { isStandardTerm, statusLabels } from '../../planner/planTable';
import { GradeSelect, YearInput, StudyYearSelect, TermSelect, StatusSelect } from './PlannerRowControls';

type Props = { publicCourses: PublicCourse[]; disabled: boolean; onChangePublicCourse: (id: string, patch: Partial<Omit<PublicCourse, 'id' | 'credits'>>) => void; onRemovePublicCourse: (id: string) => void };
const control = 'w-full rounded-sm border border-gray-300 bg-white p-2 text-sm disabled:opacity-50';
const groups: Array<[1 | 2 | 3 | 4 | null, string]> = [[1, '1年'], [2, '2年'], [3, '3年'], [4, '4年'], [null, '未設定']];
function PublicRow({ course, props }: { course: PublicCourse; props: Props }) { const [open, setOpen] = useState(false); const [title, setTitle] = useState(course.title); return <><tr className="border-b border-gray-100 align-top"><td className="p-3">{course.studyYear === null ? '未設定' : `${course.studyYear}年`}</td><td className="p-3">{course.plannedTerm === null ? '—' : isStandardTerm(course.plannedTerm) ? course.plannedTerm : '保存済み（要確認）'}</td><td className="p-3"><p className="font-medium">{course.title}</p><p className="text-xs text-gray-500">公開科目 / {course.plannedYear ?? '年度未設定'}年度</p></td><td className="p-3 text-center">2</td><td className="p-3">公開科目</td><td className="p-3"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{statusLabels[course.status]}</span></td><td className="p-3"><GradeSelect label={`${course.title}の最終評価`} value={course.finalGrade} disabled={props.disabled} onChange={finalGrade => props.onChangePublicCourse(course.id, { finalGrade })} /></td><td className="p-3 whitespace-nowrap"><button type="button" onClick={() => setOpen(value => !value)} className="underline">{open ? '閉じる' : '開く'}</button><button type="button" disabled={props.disabled} onClick={() => props.onRemovePublicCourse(course.id)} className="ml-3 text-red-700 underline">削除</button></td></tr>{open && <tr><td colSpan={8} className="p-4"><div className="grid gap-2 sm:grid-cols-5"><label className="text-xs">科目名<input value={title} disabled={props.disabled} onChange={event => setTitle(event.target.value)} onBlur={() => title.trim() && props.onChangePublicCourse(course.id, { title: title.trim() })} className={control} /></label><label className="text-xs">年度<YearInput value={course.plannedYear} disabled={props.disabled} onChange={plannedYear => props.onChangePublicCourse(course.id, { plannedYear })} /></label><label className="text-xs">履修学年<StudyYearSelect value={course.studyYear} disabled={props.disabled} onChange={studyYear => props.onChangePublicCourse(course.id, { studyYear })} /></label><label className="text-xs">時期<TermSelect id={`public-term-${course.id}`} value={course.plannedTerm} disabled={props.disabled} onChange={plannedTerm => props.onChangePublicCourse(course.id, { plannedTerm })} /></label><label className="text-xs">状態<StatusSelect value={course.status} disabled={props.disabled} onChange={status => props.onChangePublicCourse(course.id, { status })} /></label></div></td></tr>}</>; }
function MobileCard({ children }: { children: ReactNode }) { return <div className="border-b border-gray-200 p-4 last:border-b-0">{children}</div>; }
function MobilePublicCard({ course, props }: { course: PublicCourse; props: Props }) { const [open, setOpen] = useState(false); const [title, setTitle] = useState(course.title); return <MobileCard><p className="font-medium">{course.title} 2単位</p><p className="mt-1 text-sm">公開科目 / {course.studyYear ?? '未設定'}年 / {course.plannedTerm ?? '時期未設定'}</p><p className="mt-2 text-xs">{statusLabels[course.status]}</p><label className="mt-2 block text-sm">最終評価<GradeSelect label={`${course.title}の最終評価`} value={course.finalGrade} disabled={props.disabled} onChange={finalGrade => props.onChangePublicCourse(course.id, { finalGrade })} /></label><button type="button" onClick={() => setOpen(value => !value)} className="mt-3 text-sm underline">{open ? '詳細を閉じる' : '詳細を開く'}</button><button type="button" disabled={props.disabled} onClick={() => props.onRemovePublicCourse(course.id)} className="ml-3 text-sm text-red-700 underline">削除</button>{open && <div className="mt-3 grid gap-2 border-t border-gray-200 pt-3"><label className="text-xs">科目名<input value={title} disabled={props.disabled} onChange={event => setTitle(event.target.value)} onBlur={() => title.trim() && props.onChangePublicCourse(course.id, { title: title.trim() })} className={control} /></label><label className="text-xs">年度<YearInput value={course.plannedYear} disabled={props.disabled} onChange={plannedYear => props.onChangePublicCourse(course.id, { plannedYear })} /></label><label className="text-xs">履修学年<StudyYearSelect value={course.studyYear} disabled={props.disabled} onChange={studyYear => props.onChangePublicCourse(course.id, { studyYear })} /></label><label className="text-xs">時期<TermSelect id={`mobile-public-term-${course.id}`} value={course.plannedTerm} disabled={props.disabled} onChange={plannedTerm => props.onChangePublicCourse(course.id, { plannedTerm })} /></label><label className="text-xs">状態<StatusSelect value={course.status} disabled={props.disabled} onChange={status => props.onChangePublicCourse(course.id, { status })} /></label></div>}</MobileCard>; }


export default function PublicCourseList(props: Props) {
  if (props.publicCourses.length === 0) return null;
  return <section className="border-t border-gray-200" aria-label="公開科目">
    <h3 className="bg-slate-50 px-5 py-3 font-medium text-[#002255]">公開科目</h3>
    {groups.map(([year, label]) => {
      const courses = props.publicCourses.filter(course => course.studyYear === year);
      if (!courses.length) return null;
      return <section key={label} aria-label={`公開科目 ${label}`}>
        <h4 className="px-5 pt-3 text-sm font-medium">{label}</h4>
        <div className="hidden overflow-x-auto md:block"><table className="w-full text-sm"><thead className="text-left text-xs text-gray-600"><tr>{['履修学年', '時期', '科目名', '単位', '履修形態', '状態', '最終評価', '詳細'].map(title => <th key={title} className="p-3">{title}</th>)}</tr></thead><tbody>{courses.map(course => <PublicRow key={course.id} course={course} props={props} />)}</tbody></table></div>
        <div className="md:hidden">{courses.map(course => <MobilePublicCard key={course.id} course={course} props={props} />)}</div>
      </section>;
    })}
  </section>;
}
