/* Generated by npm run build:grade-import. Edit shared/grade-import/extractor.js instead. */
"use strict";
(() => {
  // shared/grade-import/extractor.js
  var GRADES = /* @__PURE__ */ new Set(["S", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D"]);
  var clean = (value) => String(value ?? "").replace(/\u00a0/g, " ").trim();
  var numberField = (raw) => {
    const text = clean(raw).replace(/^\*/, "");
    return { raw, value: /^\d+(?:\.\d+)?$/.test(text) ? Number(text) : null };
  };
  var grade = (raw) => GRADES.has(clean(raw)) ? clean(raw) : null;
  var date = (raw) => {
    const match = clean(raw).match(/^(?:(\d{2})|\d{4})[/.年](\d{1,2})[/.月](\d{1,2})(?:日)?$/);
    if (!match) return null;
    const year = match[1] ? 2e3 + Number(match[1]) : Number(clean(raw).match(/^\d{4}/)[0]);
    const month = Number(match[2]);
    const day = Number(match[3]);
    const candidate = new Date(Date.UTC(year, month - 1, day));
    return candidate.getUTCFullYear() === year && candidate.getUTCMonth() === month - 1 && candidate.getUTCDate() === day ? `${year}-${String(month).padStart(2, "0")}-${String(day).padStart(2, "0")}` : null;
  };
  var report = (raw) => {
    const text = clean(raw);
    const marker = text.charAt(0);
    const reportDate = date(text.slice(1));
    return { raw: text, status: text === "" ? "none" : marker === "\u25CB" ? "passed" : marker === "\xD7" ? "resubmit" : marker === "*" ? "processing" : "unknown", date: reportDate };
  };
  var schooling = (cells) => ({ rawYear: cells[0], rawTerm: cells[1], rawDate: cells[2], rawCredits: cells[3], rawGrade: cells[4], year: clean(cells[0]) || null, term: clean(cells[1]) || null, date: date(cells[2]), credits: numberField(cells[3]).value, grade: grade(cells[4]) });
  var course = (cells, categoryRaw) => ({
    rawName: clean(cells[1]),
    categoryRaw,
    compositionCredits: numberField(cells[2]),
    additionalEnrollment: numberField(cells[3]),
    recognizedExemption: numberField(cells[4]),
    earnedCredits: numberField(cells[5]),
    schoolingCredits: numberField(cells[6]),
    reports: [report(cells[7]), report(cells[8]), report(cells[9]), report(cells[10])],
    creditExam: { rawDate: cells[11], rawCredits: cells[12], rawGrade: cells[13], date: date(cells[11]), credits: numberField(cells[12]).value, grade: grade(cells[13]), pendingMarker: clean(cells[12]).includes("*") },
    schoolings: [schooling(cells.slice(14, 19)), schooling(cells.slice(19, 24))]
  });
  var cellsForRow = (row) => Array.from(row.querySelectorAll("td")).filter((cell) => !cell.classList.contains("line_y_label")).map((cell) => clean(cell.textContent));
  var isCategoryRow = (cells) => cells.length === 24 && clean(cells[1]).startsWith("***");
  var isCourseRow = (cells) => cells.length === 24 && !isCategoryRow(cells) && clean(cells[1]) !== "";
  var extractRows = (rows) => {
    let categoryRaw = null;
    const courses = [];
    for (const row of rows) {
      const cells = Array.isArray(row) ? row.map(clean) : cellsForRow(row);
      if (cells.length !== 24) continue;
      if (isCategoryRow(cells)) {
        categoryRaw = clean(cells[1]);
        continue;
      }
      if (clean(cells[1]) !== "") courses.push(course(cells, categoryRaw));
    }
    return courses;
  };
  var inspectTable = (table, index) => {
    const logicalRows = Array.from(table.querySelectorAll("tr.column_even, tr.column_odd"), cellsForRow);
    const validRows = logicalRows.filter((cells) => cells.length === 24);
    const courseRows = validRows.filter(isCourseRow);
    return {
      index,
      rows: logicalRows,
      courseRows,
      rowCount: logicalRows.length,
      valid24RowCount: validRows.length,
      categoryRowCount: validRows.filter(isCategoryRow).length,
      courseRowCount: courseRows.length
    };
  };
  var diagnosticsFor = (candidates, selectedCandidateIndex = null, tieCandidateIndexes = []) => ({
    tableCandidates: candidates.map(({ index, rowCount, valid24RowCount, categoryRowCount, courseRowCount }) => ({ index, rowCount, valid24RowCount, categoryRowCount, courseRowCount })),
    selectedCandidateIndex,
    tieCandidateIndexes
  });
  var selectCandidate = (candidates) => {
    const largestCourseRowCount = Math.max(...candidates.map((candidate) => candidate.courseRowCount));
    const tied = candidates.filter((candidate) => candidate.courseRowCount === largestCourseRowCount);
    if (tied.length === 1) return { selected: tied[0], tieCandidateIndexes: [] };
    return { selected: tied[0], tieCandidateIndexes: tied.map((candidate) => candidate.index) };
  };
  var extractCurrentDocument = () => {
    const candidates = Array.from(document.querySelectorAll('table[id="seisekiTabele110"]'), inspectTable);
    if (candidates.length === 0) return { ok: false, reason: "table_not_found", diagnostics: diagnosticsFor(candidates) };
    const { selected, tieCandidateIndexes } = selectCandidate(candidates);
    const diagnostics = diagnosticsFor(candidates, selected.index, tieCandidateIndexes);
    if (selected.courseRowCount === 0) return { ok: false, reason: "course_rows_not_found", diagnostics };
    return { ok: true, value: { schemaVersion: 1, source: "hosei_web_learning_grade_table", capturedAt: (/* @__PURE__ */ new Date()).toISOString(), courses: extractRows(selected.rows) }, diagnostics };
  };

  // extension/hosei-planner-import/parser/entry.js
  globalThis.HoseiPlannerGradeExtractor = { date, report, extractRows, extractCurrentDocument };
})();
